#!/usr/bin/env python3
"""
GP2040-CE Animated Splash Screen Deploy Harness
Automates:
  1. GIF validation and conversion to 128x64 1bpp C++ header
  2. Preview GIF generation
  3. Header logic & runtime simulation tests
  4. Git commit and push to trigger GitHub Actions CI
  5. GitHub Actions run monitoring
  6. Artifact download and placement in firmware/
  7. Hardware (RPI-RP2) detection and safe reporting (NEVER auto-flashing without user confirmation)
"""

import argparse
import datetime
import json
import os
import re
import shutil
import subprocess
import sys
import time
from typing import Dict, Any, List, Optional
from PIL import Image, ImageSequence, ImageOps


def check_rpi_rp2_drive() -> Optional[str]:
    """Check if an RPI-RP2 USB drive is mounted in Windows."""
    try:
        cmd = [
            "powershell",
            "-NoProfile",
            "-Command",
            'Get-Volume | Where-Object { $_.FileSystemLabel -like "*RP*" -or $_.FileSystemLabel -eq "RPI-RP2" } | Select-Object -ExpandProperty DriveLetter',
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=5)
        letters = [l.strip() for l in result.stdout.splitlines() if l.strip()]
        if letters:
            drive_path = f"{letters[0]}:\\"
            # Verify INFO_UF2.TXT exists
            if os.path.exists(os.path.join(drive_path, "INFO_UF2.TXT")):
                return drive_path
            return drive_path
    except Exception:
        pass
    return None


def convert_gif(
    input_path: str,
    output_header: str,
    preview_path: Optional[str] = None,
    mode: str = "auto",
    threshold: int = 128,
    invert: bool = False,
    min_delay_ms: int = 33,
    max_frames: Optional[int] = None,
) -> Dict[str, Any]:
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"Input file not found: {input_path}")

    img = Image.open(input_path)
    frames = []
    delays = []
    preview_frames = []

    # Detect if input is already pure 1bpp (0, 255)
    is_pure_1bpp = True
    for frame in ImageSequence.Iterator(img):
        l_frame = frame.convert("L")
        colors = l_frame.getcolors(256)
        if colors:
            unique_vals = {c[1] for c in colors}
            if not unique_vals.issubset({0, 255}):
                is_pure_1bpp = False
                break

    target_w, target_h = 128, 64
    frame_idx = 0

    for frame in ImageSequence.Iterator(img):
        if max_frames and frame_idx >= max_frames:
            break

        duration = frame.info.get("duration", 100)
        if duration is None or duration <= 0:
            duration = 100
        if duration < min_delay_ms:
            duration = min_delay_ms
        delays.append(int(duration))

        rgba = frame.convert("RGBA")
        src_w, src_h = rgba.size

        # Fit with aspect ratio preserved
        scale = min(target_w / src_w, target_h / src_h)
        new_w = max(1, int(round(src_w * scale)))
        new_h = max(1, int(round(src_h * scale)))

        scaled = rgba.resize((new_w, new_h), Image.Resampling.NEAREST)
        canvas = Image.new("RGBA", (target_w, target_h), (0, 0, 0, 255))
        offset_x = (target_w - new_w) // 2
        offset_y = (target_h - new_h) // 2
        canvas.paste(scaled, (offset_x, offset_y), scaled)

        gray = canvas.convert("L")

        if mode == "dither":
            mono = gray.convert("1", dither=Image.Dither.FLOYDSTEINBERG)
        elif mode == "threshold" or not is_pure_1bpp:
            mono = gray.point(lambda p: 255 if p >= threshold else 0, mode="1")
        else:
            # Pure 1bpp lossless
            mono = gray.point(lambda p: 255 if p > 127 else 0, mode="1")

        if invert:
            mono = ImageOps.invert(mono.convert("L")).convert("1")

        raw_bytes = mono.tobytes()
        if len(raw_bytes) != 1024:
            raise ValueError(f"Frame {frame_idx} size mismatch: {len(raw_bytes)} bytes (expected 1024)")

        frames.append(raw_bytes)

        if preview_path:
            p_frame = mono.convert("RGB")
            p_frame = p_frame.resize((target_w * 4, target_h * 4), Image.Resampling.NEAREST)
            preview_frames.append(p_frame)

        frame_idx += 1

    total_frames = len(frames)
    total_duration_ms = sum(delays)

    cumulative = []
    current_cum = 0
    for d in delays:
        current_cum += d
        cumulative.append(current_cum)

    os.makedirs(os.path.dirname(os.path.abspath(output_header)), exist_ok=True)
    with open(output_header, "w", encoding="utf-8") as f:
        f.write("/**\n")
        f.write(f" * Auto-generated by deploy_splash.py on {datetime.datetime.now().isoformat()}\n")
        f.write(f" * Source: {os.path.basename(input_path)}\n")
        f.write(f" * Frames: {total_frames}, Total Duration: {total_duration_ms} ms\n")
        f.write(" */\n\n")
        f.write("#ifndef _SPLASH_ANIM_H_\n#define _SPLASH_ANIM_H_\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#define SPLASH_ANIM_ENABLED 1\n")
        f.write(f"#define SPLASH_ANIM_FRAME_COUNT {total_frames}\n")
        f.write(f"#define SPLASH_ANIM_TOTAL_DURATION_MS {total_duration_ms}\n\n")

        f.write(f"static const uint16_t splash_anim_delays[{total_frames}] = {{\n    ")
        f.write(", ".join(str(d) for d in delays) + "\n};\n\n")

        f.write(f"static const uint32_t splash_anim_cumulative[{total_frames}] = {{\n    ")
        f.write(", ".join(str(c) for c in cumulative) + "\n};\n\n")

        f.write(f"static const uint8_t splash_anim_frames[{total_frames}][1024] = {{\n")
        for i, frame_data in enumerate(frames):
            f.write(f"    // Frame {i} (delay: {delays[i]}ms)\n    {{\n")
            for row in range(64):
                row_bytes = frame_data[row * 16 : (row + 1) * 16]
                hex_str = ", ".join(f"0x{b:02X}" for b in row_bytes)
                f.write(f"        {hex_str},\n")
            f.write("    },\n")
        f.write("};\n\n")
        f.write("#endif // _SPLASH_ANIM_H_\n")

    if preview_path and preview_frames:
        os.makedirs(os.path.dirname(os.path.abspath(preview_path)), exist_ok=True)
        preview_frames[0].save(
            preview_path,
            save_all=True,
            append_images=preview_frames[1:],
            duration=delays,
            loop=0,
        )

    return {
        "total_frames": total_frames,
        "total_duration_ms": total_duration_ms,
        "delays": delays,
        "pure_1bpp": is_pure_1bpp,
        "header_path": os.path.abspath(output_header),
        "preview_path": os.path.abspath(preview_path) if preview_path else None,
    }


def verify_header_and_logic(header_path: str, cpp_path: str) -> None:
    """Run unit tests on the generated header and C++ screen logic."""
    assert os.path.exists(header_path), f"Header not found: {header_path}"
    with open(header_path, "r", encoding="utf-8") as f:
        content = f.read()

    frame_count = int(re.search(r"#define\s+SPLASH_ANIM_FRAME_COUNT\s+(\d+)", content).group(1))
    total_duration = int(re.search(r"#define\s+SPLASH_ANIM_TOTAL_DURATION_MS\s+(\d+)", content).group(1))

    delays = [int(x.strip()) for x in re.search(r"splash_anim_delays\[\d+\]\s*=\s*\{([^}]+)\};", content).group(1).split(",") if x.strip()]
    cumulative = [int(x.strip()) for x in re.search(r"splash_anim_cumulative\[\d+\]\s*=\s*\{([^}]+)\};", content).group(1).split(",") if x.strip()]

    assert len(delays) == frame_count, f"Delay count mismatch: {len(delays)} vs {frame_count}"
    assert sum(delays) == total_duration, f"Total duration mismatch: {sum(delays)} vs {total_duration}"
    assert cumulative[-1] == total_duration, f"Cumulative end mismatch: {cumulative[-1]} vs {total_duration}"

    # Simulation check
    simulated_frames = []
    step_ms = min(20, max(5, total_duration // (frame_count * 2)))
    for t in range(0, total_duration * 2, step_ms):
        loop_time = t % total_duration
        current = 0
        for i in range(frame_count):
            if loop_time < cumulative[i]:
                current = i
                break
        simulated_frames.append(current)
    assert len(set(simulated_frames)) == frame_count, "Not all frames reachable in runtime simulation"

    # Verify SplashScreen.cpp has unconditional loop return
    with open(cpp_path, "r", encoding="utf-8") as f:
        cpp_content = f.read()
    assert "splash_anim.h" in cpp_content, "Missing splash_anim.h in SplashScreen.cpp"
    assert "return -1;" in cpp_content, "Missing loop return -1 in SplashScreen.cpp"


def run_git_push(repo_dir: str, message: str) -> None:
    """Stage, commit, and push changes to trigger GitHub Actions."""
    subprocess.run(["git", "add", "headers/display/ui/screens/splash_anim.h"], cwd=repo_dir, check=True)
    
    # Check if there are changes to commit
    status = subprocess.run(["git", "status", "--porcelain", "headers/display/ui/screens/splash_anim.h"], cwd=repo_dir, capture_output=True, text=True, check=True)
    if status.stdout.strip():
        subprocess.run(["git", "commit", "-m", message], cwd=repo_dir, check=True)
    else:
        print("[INFO] splash_anim.h unchanged in git; proceeding with current commit.")

    print("[INFO] Pushing to remote origin release-0.7.9:main...")
    subprocess.run(["git", "push", "origin", "release-0.7.9:main"], cwd=repo_dir, check=True)


def monitor_and_download(repo: str, firmware_dir: str, timeout_sec: int = 600) -> str:
    """Monitor GitHub Actions run and download resulting .uf2 artifact."""
    print(f"[INFO] Finding workflow run in {repo}...")
    time.sleep(3)
    
    run_id = None
    for _ in range(10):
        res = subprocess.run(["gh", "run", "list", "--repo", repo, "--limit", "1", "--json", "databaseId,status,conclusion"], capture_output=True, text=True, check=True)
        runs = json.loads(res.stdout)
        if runs:
            run_id = str(runs[0]["databaseId"])
            break
        time.sleep(2)

    if not run_id:
        raise RuntimeError("Could not find triggered GitHub Actions run.")

    print(f"[INFO] Monitoring GitHub Actions run ID: {run_id}")
    watch_res = subprocess.run(["gh", "run", "watch", run_id, "--repo", repo, "--exit-status"], capture_output=False)
    if watch_res.returncode != 0:
        raise RuntimeError(f"GitHub Actions run {run_id} failed. Check logs with: gh run view {run_id} --log-failed --repo {repo}")

    print("[INFO] Build succeeded! Downloading artifact...")
    temp_download = os.path.join(firmware_dir, f"temp_run_{run_id}")
    os.makedirs(temp_download, exist_ok=True)
    subprocess.run(["gh", "run", "download", run_id, "--name", "GP2040-CE - Haute42COSMOX", "--dir", temp_download, "--repo", repo], check=True)

    # Find .uf2 file
    uf2_file = None
    for root, _, files in os.walk(temp_download):
        for f in files:
            if f.endswith(".uf2"):
                uf2_file = os.path.join(root, f)
                break
        if uf2_file:
            break

    if not uf2_file:
        raise FileNotFoundError(f"No .uf2 found in artifact download: {temp_download}")

    timestamp_str = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    stamped_uf2 = os.path.join(firmware_dir, f"GP2040-CE_0.7.9_Haute42COSMOX_{timestamp_str}.uf2")
    latest_uf2 = os.path.join(firmware_dir, "GP2040-CE_latest.uf2")

    shutil.copy2(uf2_file, stamped_uf2)
    shutil.copy2(uf2_file, latest_uf2)
    shutil.rmtree(temp_download, ignore_errors=True)

    print(f"[OK] Firmware downloaded and placed at: {latest_uf2}")
    return latest_uf2


def main():
    parser = argparse.ArgumentParser(description="GP2040-CE Animated Splash Deploy Harness")
    parser.add_argument("input_gif", help="Path to input animated GIF")
    parser.add_argument("--mode", choices=["auto", "threshold", "dither"], default="auto", help="Binarization mode")
    parser.add_argument("--threshold", type=int, default=128, help="Threshold value (0-255)")
    parser.add_argument("--invert", action="store_true", help="Invert black and white pixels")
    parser.add_argument("--min-delay", type=int, default=33, help="Minimum frame delay in ms")
    parser.add_argument("--max-frames", type=int, default=None, help="Max frame count limit")
    parser.add_argument("--no-push", action="store_true", help="Skip git push & CI build (local convert & test only)")
    parser.add_argument("--repo", default="waaaaall/GP2040-CE-custom", help="GitHub repository name")

    args = parser.parse_args()

    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    header_path = os.path.join(repo_root, "headers", "display", "ui", "screens", "splash_anim.h")
    cpp_path = os.path.join(repo_root, "src", "display", "ui", "screens", "SplashScreen.cpp")
    firmware_dir = os.path.abspath(os.path.join(repo_root, "..", "firmware"))
    preview_path = os.path.join(firmware_dir, "splash_preview.gif")

    print(f"=== [Step 1/4] Converting GIF: {args.input_gif} ===")
    info = convert_gif(
        input_path=args.input_gif,
        output_header=header_path,
        preview_path=preview_path,
        mode=args.mode,
        threshold=args.threshold,
        invert=args.invert,
        min_delay_ms=args.min_delay,
        max_frames=args.max_frames,
    )
    print(f"[OK] {info['total_frames']} frames, {info['total_duration_ms']} ms total duration")

    print("=== [Step 2/4] Verifying C++ Logic & Timings ===")
    verify_header_and_logic(header_path, cpp_path)
    print("[OK] All logic and simulation tests passed!")

    if args.no_push:
        print("\n[INFO] --no-push specified. Local conversion and tests completed successfully.")
        return

    print("=== [Step 3/4] Triggering Cloud Build (GitHub Actions) ===")
    commit_msg = f"Update animated splash: {os.path.basename(args.input_gif)} ({info['total_frames']} frames, {info['total_duration_ms']}ms)"
    run_git_push(repo_root, commit_msg)

    print("=== [Step 4/4] Monitoring Build & Downloading Firmware ===")
    latest_uf2 = monitor_and_download(args.repo, firmware_dir)

    # Check hardware connection
    rpi_drive = check_rpi_rp2_drive()

    summary = {
        "status": "SUCCESS",
        "input_gif": os.path.abspath(args.input_gif),
        "total_frames": info["total_frames"],
        "total_duration_ms": info["total_duration_ms"],
        "preview_gif": preview_path,
        "firmware_uf2": latest_uf2,
        "rpi_rp2_drive": rpi_drive,
        "flash_ready": True,
    }

    print("\n========================================================")
    print("           DEPLOY HARNESS SUMMARY (COMPLETED)")
    print("========================================================")
    print(f"Frames:       {info['total_frames']} frames ({info['total_duration_ms']} ms loop)")
    print(f"Preview:      {preview_path}")
    print(f"Firmware UF2: {latest_uf2}")
    if rpi_drive:
        print(f"Hardware:     [DETECTED] RPI-RP2 mounted at {rpi_drive}")
        print("SAFETY NOTE:  Hardware writing is NEVER automatic.")
        print(f"              Ask user confirmation before copying to {rpi_drive}")
    else:
        print("Hardware:     [NOT DETECTED] Connect controller holding BOOT button to flash.")
    print("========================================================")

    # Machine-readable output on final line
    print("__HARNESS_RESULT_JSON__:" + json.dumps(summary))


if __name__ == "__main__":
    main()
