#!/usr/bin/env python3
"""
GP2040-CE Animated Splash Screen Converter
Converts animated GIF into 128x64 1bpp C++ header for GP2040-CE OLED display.
"""

import argparse
import os
import sys
from PIL import Image, ImageSequence, ImageOps


def convert_gif_to_splash(
    input_path: str,
    output_header: str,
    preview_path: str = None,
    preview_scale: int = 4,
    mode: str = "threshold",
    threshold: int = 128,
    invert: bool = False,
    min_delay_ms: int = 33,
    max_frames: int = None,
):
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"Input file not found: {input_path}")

    img = Image.open(input_path)

    frames = []
    delays = []
    preview_frames = []

    frame_idx = 0
    for frame in ImageSequence.Iterator(img):
        if max_frames and frame_idx >= max_frames:
            break

        # Extract frame delay
        duration = frame.info.get("duration", 100)
        if duration is None or duration <= 0:
            duration = 100
        if duration < min_delay_ms:
            duration = min_delay_ms
        delays.append(int(duration))

        # Convert to RGBA to handle transparency
        rgba = frame.convert("RGBA")

        # Create 128x64 black background
        target_w, target_h = 128, 64
        canvas = Image.new("RGBA", (target_w, target_h), (0, 0, 0, 255))

        # Fit with aspect ratio preserved (using nearest neighbor for crisp pixel art)
        src_w, src_h = rgba.size
        scale = min(target_w / src_w, target_h / src_h)
        new_w = max(1, int(round(src_w * scale)))
        new_h = max(1, int(round(src_h * scale)))

        scaled = rgba.resize((new_w, new_h), Image.Resampling.NEAREST)

        # Center on canvas
        offset_x = (target_w - new_w) // 2
        offset_y = (target_h - new_h) // 2

        # Paste handling alpha transparency (transparent becomes black)
        canvas.paste(scaled, (offset_x, offset_y), scaled)

        # Convert to Grayscale
        gray = canvas.convert("L")

        # Apply Binarization
        if mode == "dither":
            # Floyd-Steinberg dithering
            mono = gray.convert("1", dither=Image.Dither.FLOYDSTEINBERG)
        else:
            # Simple thresholding
            mono = gray.point(lambda p: 255 if p >= threshold else 0, mode="1")

        # Invert if requested
        if invert:
            mono = ImageOps.invert(mono.convert("L")).convert("1")

        # Extract 1bpp raw bytes (128x64 / 8 = 1024 bytes, MSB first)
        raw_bytes = mono.tobytes()
        if len(raw_bytes) != 1024:
            raise ValueError(
                f"Unexpected byte length {len(raw_bytes)} (expected 1024)"
            )

        frames.append(raw_bytes)

        # Create preview frame
        if preview_path:
            p_frame = mono.convert("RGB")
            if preview_scale > 1:
                p_frame = p_frame.resize(
                    (target_w * preview_scale, target_h * preview_scale),
                    Image.Resampling.NEAREST,
                )
            preview_frames.append(p_frame)

        frame_idx += 1

    total_frames = len(frames)
    if total_frames == 0:
        raise ValueError("No frames extracted from GIF")

    total_duration_ms = sum(delays)

    # Compute cumulative delays for runtime O(N) lookup
    cumulative = []
    curr = 0
    for d in delays:
        curr += d
        cumulative.append(curr)

    # Generate C++ Header
    os.makedirs(os.path.dirname(os.path.abspath(output_header)), exist_ok=True)
    with open(output_header, "w", encoding="utf-8") as f:
        f.write("/**\n")
        f.write(" * Automatically generated by gif_to_splash.py\n")
        f.write(f" * Source: {os.path.basename(input_path)}\n")
        f.write(f" * Total frames: {total_frames}\n")
        f.write(f" * Total duration: {total_duration_ms} ms\n")
        f.write(" */\n\n")
        f.write("#ifndef _SPLASH_ANIM_H_\n")
        f.write("#define _SPLASH_ANIM_H_\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#define SPLASH_ANIM_ENABLED 1\n")
        f.write(f"#define SPLASH_ANIM_FRAME_COUNT {total_frames}\n")
        f.write(f"#define SPLASH_ANIM_TOTAL_DURATION_MS {total_duration_ms}\n\n")

        f.write(
            f"static const uint16_t splash_anim_delays[{total_frames}] = {{\n    "
        )
        f.write(
            ", ".join(str(d) for d in delays)
            + "\n};\n\n"
        )

        f.write(
            f"static const uint32_t splash_anim_cumulative[{total_frames}] = {{\n    "
        )
        f.write(
            ", ".join(str(c) for c in cumulative)
            + "\n};\n\n"
        )

        f.write(
            f"static const uint8_t splash_anim_frames[{total_frames}][1024] = {{\n"
        )
        for i, frame_data in enumerate(frames):
            f.write(f"    // Frame {i} (delay: {delays[i]}ms)\n    {{\n")
            # 16 bytes per line (1 row of 128 pixels)
            for row in range(64):
                row_bytes = frame_data[row * 16 : (row + 1) * 16]
                hex_str = ", ".join(f"0x{b:02X}" for b in row_bytes)
                f.write(f"        {hex_str},\n")
            f.write("    },\n")
        f.write("};\n\n")
        f.write("#endif // _SPLASH_ANIM_H_\n")

    print(
        f"[OK] Generated {output_header} with {total_frames} frames ({total_duration_ms} ms)"
    )

    # Save preview GIF
    if preview_path and preview_frames:
        os.makedirs(
            os.path.dirname(os.path.abspath(preview_path)), exist_ok=True
        )
        preview_frames[0].save(
            preview_path,
            save_all=True,
            append_images=preview_frames[1:],
            duration=delays,
            loop=0,
        )
        print(f"[OK] Saved preview GIF to {preview_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Convert animated GIF to GP2040-CE 128x64 1bpp C++ header."
    )
    parser.add_argument("input", help="Path to input GIF file")
    parser.add_argument(
        "-o",
        "--output",
        default="headers/display/ui/screens/splash_anim.h",
        help="Path to output C++ header file",
    )
    parser.add_argument(
        "-p",
        "--preview",
        default="splash_preview.gif",
        help="Path to output preview GIF",
    )
    parser.add_argument(
        "--scale",
        type=int,
        default=4,
        help="Scale factor for preview GIF (default: 4 -> 512x256)",
    )
    parser.add_argument(
        "-m",
        "--mode",
        choices=["threshold", "dither"],
        default="threshold",
        help="Binarization mode: 'threshold' (crisp dot art) or 'dither' (shading)",
    )
    parser.add_argument(
        "-t",
        "--threshold",
        type=int,
        default=128,
        help="Threshold value for binarization (0-255, default: 128)",
    )
    parser.add_argument(
        "-i",
        "--invert",
        action="store_true",
        help="Invert black and white pixels",
    )
    parser.add_argument(
        "--min-delay",
        type=int,
        default=33,
        help="Minimum frame delay in ms to protect I2C bandwidth (default: 33ms ≒ 30fps)",
    )
    parser.add_argument(
        "--max-frames",
        type=int,
        default=None,
        help="Limit number of frames to convert (optional)",
    )

    args = parser.parse_args()

    try:
        convert_gif_to_splash(
            input_path=args.input,
            output_header=args.output,
            preview_path=args.preview,
            preview_scale=args.scale,
            mode=args.mode,
            threshold=args.threshold,
            invert=args.invert,
            min_delay_ms=args.min_delay,
            max_frames=args.max_frames,
        )
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
